version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - sudo yum update -y
      - sudo yum groupinstall -y "Development Tools"
      - sudo yum install -y openssl-devel bzip2-devel libffi-devel
      - wget https://www.python.org/ftp/python/3.7.12/Python-3.7.12.tgz
      - tar xzf Python-3.7.12.tgz
      - cd Python-3.7.12
      - ./configure --enable-optimizations
      - make
      - sudo make altinstall
      - python -m pip install Flask
        
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
